### ISSUE TITLE
web-ui enhancements

### ISSUE THREAD

**Issue by death-claw** [death-claw/vripper-project#147]

**Comment by jholickysr** [comment]
Not sure if this is the place for feedback. Excellent app. I am using v5.1.0. 
One feature that would be nice ... when I copy a link (to a post) and then on the main VRipper screen (+) to add that post, a box appears and you can paste the link into the box. The box though accepts MANY links as you know. However, in order to paste the next, **you must hit enter**. I cannot paste one after the other - the parser only grabs the first line and each paste-paste-paste just appends to that line. So you must paste, enter then paste. 

The feature I would like to see (another checkbox option) would be to auto-newline after each paste.

thanks

**Comment by death-claw** [comment]
> Not sure if this is the place for feedback. Excellent app. I am using v5.1.0. One feature that would be nice ... when I copy a link (to a post) and then on the main VRipper screen (+) to add that post, a box appears and you can paste the link into the box. The box though accepts MANY links as you know. However, in order to paste the next, **you must hit enter**. I cannot paste one after the other - the parser only grabs the first line and each paste-paste-paste just appends to that line. So you must paste, enter then paste.
> 
> The feature I would like to see (another checkbox option) would be to auto-newline after each paste.
> 
> thanks

Will address in a separate issue, I too find it bothersome to hit enter each time
